// Generated by tuji-web/scripts/sync-study-choice-data.mjs. Do not edit.
package app.tuji.android.core.study

data class StudyChoiceContractCase(val name: String, val a: String, val ag: String, val b: String, val bg: String, val conflict: Boolean)
val studyChoiceContractCases = listOf(
    StudyChoiceContractCase("washbasin spaces", "washbasin", "洗手台", "wash basin", "臉盆", true),
    StudyChoiceContractCase("case and width", "WASHBASIN", "洗手台", "ｗａｓｈｂａｓｉｎ", "臉盆", true),
    StudyChoiceContractCase("unicode hyphen", "wash-basin", "洗手台", "wash‐basin", "臉盆", true),
    StudyChoiceContractCase("synonym with different gloss", "sofa", "沙發", "couch", "長沙發", true),
    StudyChoiceContractCase("token subset", "knife", "刀", "kitchen knife", "菜刀", true),
    StudyChoiceContractCase("packed gloss", "pan", "平底鍋 / 煎鍋", "skillet", "煎鍋", true),
    StudyChoiceContractCase("CJK substring", "時計", "時鐘", "腕時計", "手錶", true),
    StudyChoiceContractCase("kana variant", "石鹸", "香皂", "石けん", "肥皂", true),
    StudyChoiceContractCase("distinct near spellings", "soap", "肥皂", "soup", "湯", false),
    StudyChoiceContractCase("distinct objects", "spoon", "湯匙", "fork", "叉子", false),
    StudyChoiceContractCase("keep Japanese long vowel", "ビル", "大樓", "ビール", "啤酒", false),
    StudyChoiceContractCase("width with long vowel", "ﾋﾞｰﾙ", "啤酒", "ビール", "麥酒", true),
    StudyChoiceContractCase("keep accents", "cafe", "", "café", "", false),
)
