#!/usr/bin/env python3
"""
Write the four locale files from one merged table.

`values/` becomes **English**, not zh-Hant. That is the change this script
exists to make: `values/` is Android's fallback for every locale nobody wrote a
file for, so leaving Chinese there hands a French phone a Chinese UI. zh-Hant
moves to `values-zh-rTW/`, where it is chosen rather than defaulted to.
"""
import json
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from xml.sax.saxutils import escape

RES = Path("app/src/main/res")
OUT = {"en": "values", "zh-Hant": "values-zh-rTW", "ja": "values-ja", "zh-Hans": "values-zh-rCN"}

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by scripts/generate-locales.py — edit the source table, not this.

  `values/` is English because it is Android's fallback for every locale with no
  file of its own; zh-Hant lives in values-zh-rTW where it is chosen rather than
  defaulted to.
-->
<resources>
"""


def android_escape(text: str) -> str:
    """XML entities, plus the two characters Android itself treats specially."""
    out = escape(text)
    return out.replace("'", "\\'").replace('"', '\\"')


def main() -> int:
    merged = json.load(open(sys.argv[1]))
    # Order comes from the **source** file, not from `values/`: zh-Hant is what
    # the strings are written in, and English is one of the outputs.
    order = [
        e.get("name")
        for e in ET.parse(RES / "values-zh-rTW/strings.xml").getroot().findall("string")
    ]

    for lang, folder in OUT.items():
        rows = []
        for name in order:
            value = merged.get(name, {}).get(lang)
            if value is None:
                print(f"missing {lang}/{name}", file=sys.stderr)
                return 1
            rows.append(f'    <string name="{name}">{android_escape(value)}</string>')
        path = RES / folder / "strings.xml"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(HEADER + "\n".join(rows) + "\n</resources>\n")
        print(f"{folder}/strings.xml  {len(rows)} strings")
    return 0


if __name__ == "__main__":
    sys.exit(main())
